name: renko-algo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ta-lib
  - pip:
    - pandas>=1.3.0
    - numpy>=1.21.0
    - matplotlib>=3.4.0
    - backtrader>=1.9.76.123
    - mplfinance>=0.12.9b7 
    - pyyaml>=6.0.2
    - akshare>=1.1.0