# 回测相关配置
backtest_config:
  max_iterations: 100000        # 最大迭代次数
  max_workers: 4               # 并行执行的最大工作线程数
  initial_capital: 1000000     # 初始资金
  recent_signal_days: 3        # 仅考虑最近N天的信号

# 优化参数设置
optimization_parameters:
  atr_periods: [3, 5, 10, 15]          # ATR（平均真实波幅）周期的可选值
  atr_multipliers: [0.5, 1.0, 2.0]     # ATR乘数的可选值
  trend_lengths: [2, 3, 5]             # 趋势长度的可选值 