# 是否使用数据库缓存
use_db_cache: true
# 是否使用本地CSV缓存
use_csv_cache: false
# 回测相关配置
backtest_config:
  max_iterations: 100000        # 最大迭代次数
  max_threads: 4               # 并行执行的最大工作线程数
  initial_capital: 1000000     # 初始资金
  recent_signal_days: 2        # 仅考虑最近N天的信号
  target_return: 15            # 目标收益率（百分比）

# 优化参数设置
optimization_parameters:
  atr_periods: [3, 5, 10, 15]          # ATR（平均真实波幅）周期的可选值
  atr_multipliers: [0.5, 0.7]     # ATR乘数的可选值
  trend_lengths: [2, 3]             # 趋势长度的可选值

# 数据源配置
query_method: yfinance              # 数据源方式，可选值：akshare、yfinance